// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFormsField = "forms_fields"

// FormsField mapped from table <forms_fields>
type FormsField struct {
	FieldID         string    `gorm:"column:field_id;primaryKey" json:"field_id"`
	FormID          string    `gorm:"column:form_id;not null" json:"form_id"`
	Label           string    `gorm:"column:label;not null" json:"label"`
	Type            string    `gorm:"column:type;not null" json:"type"`
	Required        bool      `gorm:"column:required;not null" json:"required"`
	Placeholder     string    `gorm:"column:placeholder;not null" json:"placeholder"`
	ValidationRules *string   `gorm:"column:validation_rules" json:"validation_rules"`
	Options         *string   `gorm:"column:options" json:"options"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName FormsField's table name
func (*FormsField) TableName() string {
	return TableNameFormsField
}
