// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFormsAggregate = "forms_aggregate"

// FormsAggregate mapped from table <forms_aggregate>
type FormsAggregate struct {
	FormID     string    `gorm:"column:form_id;primaryKey" json:"form_id"`
	FormName   string    `gorm:"column:form_name;primaryKey" json:"form_name"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	RelatedIds *string   `gorm:"column:related_ids" json:"related_ids"`
}

// TableName FormsAggregate's table name
func (*FormsAggregate) TableName() string {
	return TableNameFormsAggregate
}
