// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFormFieldsAggregate = "form_fields_aggregate"

// FormFieldsAggregate mapped from table <form_fields_aggregate>
type FormFieldsAggregate struct {
	FieldID   string    `gorm:"column:field_id;primaryKey;default:uuid()" json:"field_id"`
	FormID    string    `gorm:"column:form_id;not null" json:"form_id"`
	Label     string    `gorm:"column:label;not null" json:"label"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName FormFieldsAggregate's table name
func (*FormFieldsAggregate) TableName() string {
	return TableNameFormFieldsAggregate
}
