// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFormsAggregate = "forms_aggregate"

// FormsAggregate mapped from table <forms_aggregate>
type FormsAggregate struct {
	FormID    string `gorm:"column:form_id;primaryKey" json:"form_id"`
	FieldID   string `gorm:"column:field_id;primaryKey" json:"field_id"`
	FormName  string `gorm:"column:form_name;not null" json:"form_name"`
	FieldName string `gorm:"column:field_name;not null" json:"field_name"`
}

// TableName FormsAggregate's table name
func (*FormsAggregate) TableName() string {
	return TableNameFormsAggregate
}
