// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameHousePropertyMedia = "house_property_medias"

// HousePropertyMedia mapped from table <house_property_medias>
type HousePropertyMedia struct {
	ID              string         `gorm:"column:id;primaryKey" json:"id"`
	HousePropertyID string         `gorm:"column:house_property_id;not null" json:"house_property_id"`
	URL             string         `gorm:"column:url;not null" json:"url"`
	Type            string         `gorm:"column:type;not null" json:"type"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt       time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName HousePropertyMedia's table name
func (*HousePropertyMedia) TableName() string {
	return TableNameHousePropertyMedia
}
