// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameHouseProperty = "house_property"

// HouseProperty mapped from table <house_property>
type HouseProperty struct {
	ID                string         `gorm:"column:id;primaryKey" json:"id"`
	Purpose           string         `gorm:"column:purpose;not null" json:"purpose"`
	TransactionType   string         `gorm:"column:transaction_type;not null" json:"transaction_type"`
	HouseStatus       *string        `gorm:"column:house_status" json:"house_status"`
	OwnerName         string         `gorm:"column:owner_name;not null" json:"owner_name"`
	Phone             string         `gorm:"column:phone;not null" json:"phone"`
	CommunityAddress  string         `gorm:"column:community_address;not null" json:"community_address"`
	FloorRangeMin     *int32         `gorm:"column:floor_range_min" json:"floor_range_min"`
	FloorRangeMax     *int32         `gorm:"column:floor_range_max" json:"floor_range_max"`
	BuildingNumber    *int32         `gorm:"column:building_number" json:"building_number"`
	UnitNumber        *int32         `gorm:"column:unit_number" json:"unit_number"`
	DoorNumber        *int32         `gorm:"column:door_number" json:"door_number"`
	FloorNumber       *int32         `gorm:"column:floor_number" json:"floor_number"`
	FloorNumberFrom   *int32         `gorm:"column:floor_number_from" json:"floor_number_from"`
	FloorNumberTo     *int32         `gorm:"column:floor_number_to" json:"floor_number_to"`
	Title             *string        `gorm:"column:title" json:"title"`
	CarHeight         *float64       `gorm:"column:car_height" json:"car_height"`
	LayoutRoom        *int32         `gorm:"column:layout_room" json:"layout_room"`
	LayoutHall        *int32         `gorm:"column:layout_hall" json:"layout_hall"`
	LayoutKitchen     *int32         `gorm:"column:layout_kitchen" json:"layout_kitchen"`
	LayoutBathroom    *int32         `gorm:"column:layout_bathroom" json:"layout_bathroom"`
	LayoutBalcony     *int32         `gorm:"column:layout_balcony" json:"layout_balcony"`
	Stairs            *int32         `gorm:"column:stairs" json:"stairs"`
	Rooms             *int32         `gorm:"column:rooms" json:"rooms"`
	ActualRate        *float64       `gorm:"column:actual_rate" json:"actual_rate"`
	Level             *int32         `gorm:"column:level" json:"level"`
	FloorHeight       *float64       `gorm:"column:floor_height" json:"floor_height"`
	ProgressDepth     *float64       `gorm:"column:progress_depth" json:"progress_depth"`
	DoorWidth         *float64       `gorm:"column:door_width" json:"door_width"`
	BuildingArea      int32          `gorm:"column:building_area;not null" json:"building_area"`
	UseArea           float64        `gorm:"column:use_area;not null" json:"use_area"`
	SalePrice         float64        `gorm:"column:sale_price;not null;default:0.00" json:"sale_price"`
	RentPrice         float64        `gorm:"column:rent_price;not null;default:0.00" json:"rent_price"`
	RentLowPrice      *float64       `gorm:"column:rent_low_price" json:"rent_low_price"`
	DownPayment       *float64       `gorm:"column:down_payment" json:"down_payment"`
	SaleLowPrice      *float64       `gorm:"column:sale_low_price" json:"sale_low_price"`
	HouseType         *string        `gorm:"column:house_type" json:"house_type"`
	HouseOrientation  *string        `gorm:"column:house_orientation" json:"house_orientation"`
	HouseDecoration   *string        `gorm:"column:house_decoration" json:"house_decoration"`
	DiscountYearLimit *int32         `gorm:"column:discount_year_limit" json:"discount_year_limit"`
	ViewMethod        *string        `gorm:"column:view_method" json:"view_method"`
	PaymentMethod     *string        `gorm:"column:payment_method" json:"payment_method"`
	PropertyTax       *float64       `gorm:"column:property_tax" json:"property_tax"`
	BuildingStructure *string        `gorm:"column:building_structure" json:"building_structure"`
	BuildingYear      *string        `gorm:"column:building_year" json:"building_year"`
	PropertyRights    *string        `gorm:"column:property_rights" json:"property_rights"`
	PropertyYearLimit *int32         `gorm:"column:property_year_limit" json:"property_year_limit"`
	CertificateDate   *time.Time     `gorm:"column:certificate_date" json:"certificate_date"`
	HandoverDate      *time.Time     `gorm:"column:handover_date" json:"handover_date"`
	Degree            *string        `gorm:"column:degree" json:"degree"`
	Household         *string        `gorm:"column:household" json:"household"`
	Source            *string        `gorm:"column:source" json:"source"`
	DelegateNumber    *string        `gorm:"column:delegate_number" json:"delegate_number"`
	UniqueHousing     *bool          `gorm:"column:unique_housing" json:"unique_housing"`
	FullPayment       *bool          `gorm:"column:full_payment" json:"full_payment"`
	Mortgage          *bool          `gorm:"column:mortgage" json:"mortgage"`
	Urgent            *bool          `gorm:"column:urgent" json:"urgent"`
	Support           *string        `gorm:"column:support" json:"support"`
	PresentState      *string        `gorm:"column:present_state" json:"present_state"`
	ExternalSync      bool           `gorm:"column:external_sync;not null" json:"external_sync"`
	Remark            *string        `gorm:"column:remark" json:"remark"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt         time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName HouseProperty's table name
func (*HouseProperty) TableName() string {
	return TableNameHouseProperty
}
