// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameHousePropertyHistory = "house_property_history"

// HousePropertyHistory mapped from table <house_property_history>
type HousePropertyHistory struct {
	ID                string         `gorm:"column:id;primaryKey" json:"id"`
	HousePropertyID   string         `gorm:"column:house_property_id;not null" json:"house_property_id"`
	HousePropertyData string         `gorm:"column:house_property_data;not null" json:"house_property_data"`
	DeletedAt         gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt         time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName HousePropertyHistory's table name
func (*HousePropertyHistory) TableName() string {
	return TableNameHousePropertyHistory
}
