// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHousePropertyTag = "house_property_tags"

// HousePropertyTag mapped from table <house_property_tags>
type HousePropertyTag struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Tag             string    `gorm:"column:tag;not null" json:"tag"`
	HousePropertyID string    `gorm:"column:house_property_id;not null" json:"house_property_id"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName HousePropertyTag's table name
func (*HousePropertyTag) TableName() string {
	return TableNameHousePropertyTag
}
