// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameHousePropertyAggregate = "house_property_aggregate"

// HousePropertyAggregate mapped from table <house_property_aggregate>
type HousePropertyAggregate struct {
	ID        string         `gorm:"column:id;primaryKey" json:"id"`
	Address   string         `gorm:"column:address;not null" json:"address"`
	IsSynced  bool           `gorm:"column:is_synced;not null" json:"is_synced"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt *time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName HousePropertyAggregate's table name
func (*HousePropertyAggregate) TableName() string {
	return TableNameHousePropertyAggregate
}
