// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameLocation = "locations"

// Location mapped from table <locations>
type Location struct {
	ID        string         `gorm:"column:id;primaryKey" json:"id"`
	Latitude  *float64       `gorm:"column:latitude" json:"latitude"`
	Longitude *float64       `gorm:"column:longitude" json:"longitude"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Location's table name
func (*Location) TableName() string {
	return TableNameLocation
}
