// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRoleAggregate = "role_aggregate"

// RoleAggregate mapped from table <role_aggregate>
type RoleAggregate struct {
	ID            string    `gorm:"column:id;primaryKey" json:"id"`
	Name          string    `gorm:"column:name;not null" json:"name"`
	PermissionIds string    `gorm:"column:permission_ids;not null" json:"permission_ids"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName RoleAggregate's table name
func (*RoleAggregate) TableName() string {
	return TableNameRoleAggregate
}
