// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID            string         `gorm:"column:id;primaryKey" json:"id"`
	Username      string         `gorm:"column:username;not null" json:"username"`
	Email         *string        `gorm:"column:email" json:"email"`
	Phone         *string        `gorm:"column:phone" json:"phone"`
	FullName      *string        `gorm:"column:full_name" json:"full_name"`
	AvatarURL     *string        `gorm:"column:avatar_url" json:"avatar_url"`
	Gender        *string        `gorm:"column:gender" json:"gender"`
	Birthday      *time.Time     `gorm:"column:birthday" json:"birthday"`
	Address       *string        `gorm:"column:address" json:"address"`
	PasswordHash  string         `gorm:"column:password_hash;not null" json:"password_hash"`
	Role          *string        `gorm:"column:role" json:"role"`
	Status        *string        `gorm:"column:status" json:"status"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	LastLoginAt   *time.Time     `gorm:"column:last_login_at" json:"last_login_at"`
	LoginAttempts *int32         `gorm:"column:login_attempts" json:"login_attempts"`
	Preferences   *string        `gorm:"column:preferences" json:"preferences"`
	Tags          *string        `gorm:"column:tags" json:"tags"`
	ReferredBy    *string        `gorm:"column:referred_by" json:"referred_by"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
