// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserAggregate = "user_aggregate"

// UserAggregate mapped from table <user_aggregate>
type UserAggregate struct {
	UserID       string         `gorm:"column:user_id;primaryKey" json:"user_id"`
	Username     string         `gorm:"column:username;not null" json:"username"`
	PasswordHash string         `gorm:"column:password_hash;not null" json:"password_hash"`
	Status       *string        `gorm:"column:status" json:"status"`
	Role         *string        `gorm:"column:role" json:"role"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	CreatedAt    time.Time      `gorm:"column:created_at;autoCreateTime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;autoUpdateTime;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UserAggregate's table name
func (*UserAggregate) TableName() string {
	return TableNameUserAggregate
}
