// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"strings"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/r1005410078/meida-admin-server/internal/infrastructure/dao/model"
)

func newUserPermission(db *gorm.DB, opts ...gen.DOOption) userPermission {
	_userPermission := userPermission{}

	_userPermission.userPermissionDo.UseDB(db, opts...)
	_userPermission.userPermissionDo.UseModel(&model.UserPermission{})

	tableName := _userPermission.userPermissionDo.TableName()
	_userPermission.ALL = field.NewAsterisk(tableName)
	_userPermission.ID = field.NewString(tableName, "id")
	_userPermission.Name = field.NewString(tableName, "name")
	_userPermission.Description = field.NewString(tableName, "description")
	_userPermission.Action = field.NewString(tableName, "action")
	_userPermission.CreateAt = field.NewTime(tableName, "create_at")
	_userPermission.UpdatedAt = field.NewTime(tableName, "updated_at")

	_userPermission.fillFieldMap()

	return _userPermission
}

type userPermission struct {
	userPermissionDo

	ALL         field.Asterisk
	ID          field.String
	Name        field.String
	Description field.String
	Action      field.String
	CreateAt    field.Time
	UpdatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (u userPermission) Table(newTableName string) *userPermission {
	u.userPermissionDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userPermission) As(alias string) *userPermission {
	u.userPermissionDo.DO = *(u.userPermissionDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userPermission) updateTableName(table string) *userPermission {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewString(table, "id")
	u.Name = field.NewString(table, "name")
	u.Description = field.NewString(table, "description")
	u.Action = field.NewString(table, "action")
	u.CreateAt = field.NewTime(table, "create_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *userPermission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userPermission) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 6)
	u.fieldMap["id"] = u.ID
	u.fieldMap["name"] = u.Name
	u.fieldMap["description"] = u.Description
	u.fieldMap["action"] = u.Action
	u.fieldMap["create_at"] = u.CreateAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u userPermission) clone(db *gorm.DB) userPermission {
	u.userPermissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userPermission) replaceDB(db *gorm.DB) userPermission {
	u.userPermissionDo.ReplaceDB(db)
	return u
}

type userPermissionDo struct{ gen.DO }

type IUserPermissionDo interface {
	gen.SubQuery
	Debug() IUserPermissionDo
	WithContext(ctx context.Context) IUserPermissionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserPermissionDo
	WriteDB() IUserPermissionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserPermissionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserPermissionDo
	Not(conds ...gen.Condition) IUserPermissionDo
	Or(conds ...gen.Condition) IUserPermissionDo
	Select(conds ...field.Expr) IUserPermissionDo
	Where(conds ...gen.Condition) IUserPermissionDo
	Order(conds ...field.Expr) IUserPermissionDo
	Distinct(cols ...field.Expr) IUserPermissionDo
	Omit(cols ...field.Expr) IUserPermissionDo
	Join(table schema.Tabler, on ...field.Expr) IUserPermissionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserPermissionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserPermissionDo
	Group(cols ...field.Expr) IUserPermissionDo
	Having(conds ...gen.Condition) IUserPermissionDo
	Limit(limit int) IUserPermissionDo
	Offset(offset int) IUserPermissionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserPermissionDo
	Unscoped() IUserPermissionDo
	Create(values ...*model.UserPermission) error
	CreateInBatches(values []*model.UserPermission, batchSize int) error
	Save(values ...*model.UserPermission) error
	First() (*model.UserPermission, error)
	Take() (*model.UserPermission, error)
	Last() (*model.UserPermission, error)
	Find() ([]*model.UserPermission, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserPermission, err error)
	FindInBatches(result *[]*model.UserPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserPermission) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserPermissionDo
	Assign(attrs ...field.AssignExpr) IUserPermissionDo
	Joins(fields ...field.RelationField) IUserPermissionDo
	Preload(fields ...field.RelationField) IUserPermissionDo
	FirstOrInit() (*model.UserPermission, error)
	FirstOrCreate() (*model.UserPermission, error)
	FindByPage(offset int, limit int) (result []*model.UserPermission, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserPermissionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler

	FilterWithNameAndRole(name string, role string) (result []model.UserPermission, err error)
}

// SELECT * FROM @@table WHERE name = @name{{if role !=""}} AND role = @role{{end}}
func (u userPermissionDo) FilterWithNameAndRole(name string, role string) (result []model.UserPermission, err error) {
	var params []interface{}

	var generateSQL strings.Builder
	params = append(params, name)
	generateSQL.WriteString("SELECT * FROM user_permissions WHERE name = ? ")
	if role != "" {
		params = append(params, role)
		generateSQL.WriteString("AND role = ? ")
	}

	var executeSQL *gorm.DB
	executeSQL = u.UnderlyingDB().Raw(generateSQL.String(), params...).Find(&result) // ignore_security_alert
	err = executeSQL.Error

	return
}

func (u userPermissionDo) Debug() IUserPermissionDo {
	return u.withDO(u.DO.Debug())
}

func (u userPermissionDo) WithContext(ctx context.Context) IUserPermissionDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userPermissionDo) ReadDB() IUserPermissionDo {
	return u.Clauses(dbresolver.Read)
}

func (u userPermissionDo) WriteDB() IUserPermissionDo {
	return u.Clauses(dbresolver.Write)
}

func (u userPermissionDo) Session(config *gorm.Session) IUserPermissionDo {
	return u.withDO(u.DO.Session(config))
}

func (u userPermissionDo) Clauses(conds ...clause.Expression) IUserPermissionDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userPermissionDo) Returning(value interface{}, columns ...string) IUserPermissionDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userPermissionDo) Not(conds ...gen.Condition) IUserPermissionDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userPermissionDo) Or(conds ...gen.Condition) IUserPermissionDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userPermissionDo) Select(conds ...field.Expr) IUserPermissionDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userPermissionDo) Where(conds ...gen.Condition) IUserPermissionDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userPermissionDo) Order(conds ...field.Expr) IUserPermissionDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userPermissionDo) Distinct(cols ...field.Expr) IUserPermissionDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userPermissionDo) Omit(cols ...field.Expr) IUserPermissionDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userPermissionDo) Join(table schema.Tabler, on ...field.Expr) IUserPermissionDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userPermissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserPermissionDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userPermissionDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserPermissionDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userPermissionDo) Group(cols ...field.Expr) IUserPermissionDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userPermissionDo) Having(conds ...gen.Condition) IUserPermissionDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userPermissionDo) Limit(limit int) IUserPermissionDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userPermissionDo) Offset(offset int) IUserPermissionDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userPermissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserPermissionDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userPermissionDo) Unscoped() IUserPermissionDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userPermissionDo) Create(values ...*model.UserPermission) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userPermissionDo) CreateInBatches(values []*model.UserPermission, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userPermissionDo) Save(values ...*model.UserPermission) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userPermissionDo) First() (*model.UserPermission, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserPermission), nil
	}
}

func (u userPermissionDo) Take() (*model.UserPermission, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserPermission), nil
	}
}

func (u userPermissionDo) Last() (*model.UserPermission, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserPermission), nil
	}
}

func (u userPermissionDo) Find() ([]*model.UserPermission, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserPermission), err
}

func (u userPermissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserPermission, err error) {
	buf := make([]*model.UserPermission, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userPermissionDo) FindInBatches(result *[]*model.UserPermission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userPermissionDo) Attrs(attrs ...field.AssignExpr) IUserPermissionDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userPermissionDo) Assign(attrs ...field.AssignExpr) IUserPermissionDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userPermissionDo) Joins(fields ...field.RelationField) IUserPermissionDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userPermissionDo) Preload(fields ...field.RelationField) IUserPermissionDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userPermissionDo) FirstOrInit() (*model.UserPermission, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserPermission), nil
	}
}

func (u userPermissionDo) FirstOrCreate() (*model.UserPermission, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserPermission), nil
	}
}

func (u userPermissionDo) FindByPage(offset int, limit int) (result []*model.UserPermission, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userPermissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userPermissionDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userPermissionDo) Delete(models ...*model.UserPermission) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userPermissionDo) withDO(do gen.Dao) *userPermissionDo {
	u.DO = *do.(*gen.DO)
	return u
}
