POST http://127.0.0.1:8080/v1/role/save
User-Agent: vscode-restclient
content-type: application/json

{ "name": "ddddd", "description": "测试", "permissionIds": ["4456047d-c03a-11ef-81db-0242ac110003"] }

###
POST http://127.0.0.1:8080/v1/role/save
User-Agent: vscode-restclient
content-type: application/json

{ "id": "da11f1bb-5727-4d79-bdcc-78e526e10362", "description": "测试2222", "permissionIds": ["47491771-c03a-11ef-81db-0242ac110003"] }

###
GEt http://127.0.0.1:8080/v1/role/list
User-Agent: vscode-restclient
content-type: application/json

###
DELETE http://127.0.0.1:8080/v1/role/delete/da11f1bb-5727-4d79-bdcc-78e526e10362
